### ISSUE TITLE
Error on embedPng

### ISSUE THREAD

**Issue by thantos** [cantoo-scribe/pdf-lib#33]
### What were you trying to do?

embedPng

### How did you attempt to do it?

pdfDoc.embedPng using esm

### What actually happened?

UPNG.decode is not a function

### What did you expect to happen?

no error

### How can we reproduce the issue?

Run using ESM

### Version

 1.19.14 

### What environment are you running pdf-lib in?

Node

### Checklist

- [X] My report includes a Short, Self Contained, Correct (Compilable) Example.
- [X] I have attached all PDFs, images, and other files needed to run my SSCCE.

### Additional Notes

Worked in 1.17

**Comment by Sharcoux** [comment]
Can you provide the exact code you're trying to run and the exact and complete error log?

**Comment by thantos** [comment]
```
    TypeError: UPNG.decode is not a function

      27 |       embedImage(pdfDoc, await pdfDoc.embedJpg(pdf.contents));
      28 |     } else if (pdf.contentType === "image/png") {
    > 29 |       embedImage(pdfDoc, await pdfDoc.embedPng(pdf.contents));
         |                                       ^
      30 |     } else {
      31 |       throw new Error(`Unsupported content type: ${pdf.contentType}`);
      32 |     }

      at new PNG (../../node_modules/.pnpm/@cantoo+pdf-lib@1.19.14/node_modules/@cantoo/pdf-lib/src/utils/png.ts:51:23)
      at Function.PNG.load (../../node_modules/.pnpm/@cantoo+pdf-lib@1.19.14/node_modules/@cantoo/pdf-lib/src/utils/png.ts:41:42)
      at Function.<anonymous> (../../node_modules/.pnpm/@cantoo+pdf-lib@1.19.14/node_modules/@cantoo/pdf-lib/src/core/embedders/PngEmbedder.ts:12:21)
      at ../../node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:169:75
      at __awaiter (../../node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:165:16)
      at Function.for (../../node_modules/.pnpm/@cantoo+pdf-lib@1.19.14/node_modules/@cantoo/pdf-lib/es/core/embedders/PngEmbedder.js:17:16)
      at PDFDocument.<anonymous> (../../node_modules/.pnpm/@cantoo+pdf-lib@1.19.14/node_modules/@cantoo/pdf-lib/src/api/PDFDocument.ts:1100:43)
      at ../../node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:169:75
      at __awaiter (../../node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:165:16)
      at PDFDocument.embedPng (../../node_modules/.pnpm/@cantoo+pdf-lib@1.19.14/node_modules/@cantoo/pdf-lib/es/api/PDFDocument.js:957:16)
```

**Comment by thantos** [comment]
Confirmed that the same code works on 1.17

**Comment by Sharcoux** [comment]
I'll be closing this if I get no answer.
